civica-digital/sociedad-actua

app/views/visitors/index.html.erb

Closes https://www.pivotaltracker.com/story/show/106029542

Finished the temporal basic landing page

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb

Closes https://www.pivotaltracker.com/story/show/106334654

Finished editing the footer params

---

app/controllers/collaborators_controller.rb
app/models/collaborator.rb
app/views/collaborators/index.html.erb
app/views/collaborators/new.html.erb
app/views/collaborators/show.html.erb
config/routes.rb
db/migrate/20151022024953_create_collaborator.rb
db/schema.rb
spec/factories/collaborators.rb
spec/features/add_new_collaborators_spec.rb
spec/models/collaborator_spec.rb
spec/support/helpers.rb
spec/support/helpers/account.rb

Completa el perfil después de crear una cuenta para ser colaborador.

Agrega el perfil Colaborador

---

app/models/organization.rb
db/schema.rb

validaciones de campos en el formulario de organizaciones

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_multiple_chosen.scss
app/controllers/investors_controller.rb
app/models/investor.rb
app/views/investors/new.html.haml

Hotfix: https://www.pivotaltracker.com/story/show/104524376

Support for multiple select for investor causes

---

Gemfile
Gemfile.lock
config/initializers/routes.rb
config/locales/routes.es.yml
config/routes.rb

Closes https://www.pivotaltracker.com/story/show/106490398

added translations to the routes

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb

Closes https://www.pivotaltracker.com/story/show/106706542

added dosis fonts to the project

---

app/controllers/organizations_controller.rb
app/views/organizations/new.html.haml

https://www.pivotaltracker.com/story/show/106805132

add checkbox to organization view

---

app/models/investor.rb
app/models/organization.rb
db/schema.rb

https://www.pivotaltracker.com/story/show/106781000

Validations investor

---

app/assets/stylesheets/components/_navbar.scss
app/views/layouts/_top_navbar.html.haml

Closes https://www.pivotaltracker.com/story/show/106877858

The logo now redirects home

---

app/models/collaborator.rb
app/models/investor.rb
app/models/organization.rb
config/locales/collaborator.yml
config/locales/investor.yml
config/locales/organization.yml
db/schema.rb

https://www.pivotaltracker.com/story/show/106883992

Validation update

---

app/views/devise/sessions/new.html.haml
config/locales/user.yml

Closes https://www.pivotaltracker.com/story/show/106027062

Added translations for the sign in labels

---

app/views/layouts/_footer.html.haml
db/schema.rb

https://www.pivotaltracker.com/story/show/106783484

add link to github

---

app/controllers/projects_controller.rb
config/locales/collaborator.yml
config/locales/devise.es.yml
config/locales/es.yml
config/locales/organization.yml
config/locales/project.yml
config/locales/simple_form.es.yml
config/locales/user.yml

solves: 
https://www.pivotaltracker.com/story/show/106797994
https://www.pivotaltracker.com/story/show/106879260

Adds some i18n and copys on projects and orgs

---

Gemfile
Gemfile.lock
app/mailers/user_mailer.rb
app/models/user.rb
app/views/user_mailer/welcome_email.html.erb
config/environments/development.rb
config/locales/user.yml

Solves: https://www.pivotaltracker.com/story/show/106972212

Adds UserMailer welcome email

---

app/assets/stylesheets/elements/_input.scss
app/views/collaborators/_form.html.haml
app/views/investors/_form.html.haml
app/views/organizations/_form.html.haml
config/locales/collaborator.yml
config/locales/investor.yml
config/locales/organization.yml

https://www.pivotaltracker.com/story/show/106887192

Label form

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_multiple_chosen.scss
app/assets/stylesheets/elements/_text.scss

Solves:
https://www.pivotaltracker.com/story/show/106944852
https://www.pivotaltracker.com/story/show/106880810

Form input labels colors

---

app/controllers/organizations_controller.rb
app/models/organization.rb
app/views/organizations/_form.html.haml
config/locales/organization.yml
db/migrate/20151031005215_add_url_profile.rb
db/schema.rb

https://www.pivotaltracker.com/story/show/106887192

Form input/organization

---

app/controllers/visitors_controller.rb
app/models/user.rb
app/views/devise/registrations/new.html.haml
config/initializers/devise.rb
config/locales/user.yml

Solves:
https://www.pivotaltracker.com/story/show/107001152

Acepta Políticas de uso al registrarme como usuario

---

app/controllers/investors_controller.rb
app/models/investor.rb
app/views/investors/_form.html.haml
config/locales/investor.yml
db/migrate/20151030230025_change_investor_table.rb
db/schema.rb

https://www.pivotaltracker.com/story/show/106887300

Form input/investor

---

app/controllers/collaborators_controller.rb
app/controllers/investors_controller.rb
app/controllers/organizations_controller.rb
app/controllers/projects_controller.rb
app/views/collaborators/_form.html.haml
app/views/investors/_form.html.haml
app/views/organizations/_form.html.haml
app/views/projects/_form.html.haml
config/locales/collaborator.yml
config/locales/investor.yml
config/locales/organization.yml
config/locales/project.yml
db/migrate/20151102220454_add_other_causes.rb
db/migrate/20151102220454_add_other_causes_organization.rb
db/schema.rb

https://www.pivotaltracker.com/story/show/106806366

Add other causes

---

app/views/organizations/_form.html.haml

https://www.pivotaltracker.com/story/show/107087134

add toggle to organizations

---

app/models/collaborator.rb
app/views/collaborators/_form.html.haml

https://www.pivotaltracker.com/story/show/107238252

agregar opcion de Investigador(a)

---

app/models/collaborator.rb
app/models/investor.rb
app/models/organization.rb
config/locales/collaborator.yml

https://www.pivotaltracker.com/story/show/107236154

se deja como opcional las validaciones de http https

---

app/uploaders/logo_uploader.rb

Solves: https://www.pivotaltracker.com/story/show/106798084

Accepts JPEG on logo uploader

---

app/assets/javascripts/collaborator.coffee
app/assets/stylesheets/components/_forms.scss
app/controllers/organizations_controller.rb
app/controllers/projects_controller.rb
app/helpers/organizations_helper.rb
app/models/organization.rb
app/views/collaborators/_form.html.haml
app/views/collaborators/edit.html.haml
app/views/layouts/_footer.html.haml
app/views/organizations/_form.html.haml
app/views/organizations/edit.html.haml
app/views/projects/_form.html.haml
app/views/projects/new.html.haml
config/locales/collaborator.yml
config/locales/organization.yml
config/locales/project.yml

Solves:
https://www.pivotaltracker.com/story/show/106887192

Refactor markup and design organization profile form

---

app/models/project.rb

https://www.pivotaltracker.com/story/show/106786208

serialize causes

---

app/controllers/search/projects_controller.rb
app/models/project.rb
app/views/layouts/_sub_navbar.html.haml
app/views/search/projects/index.html.haml
config/routes.rb

Closes https://www.pivotaltracker.com/story/show/105258416

Added a full text search on projects params and organization name

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_video.scss
app/views/visitors/index.html.haml

https://www.pivotaltracker.com/story/show/107351840
Pending:

[WIP] Video on landing

---

app/views/layouts/_footer.html.haml

Closes https://www.pivotaltracker.com/story/show/107362896

Rehabilitated the footer links

---

app/assets/stylesheets/defaults/_colors.scss

Closes https://www.pivotaltracker.com/story/show/107363866

Changed the accent colors that goes in multiple helpers

---

app/views/visitors/index.html.haml

Closes https://www.pivotaltracker.com/story/show/107362936

Links which were for registration are now for exploring resources

---

app/assets/javascripts/ project.coffee

Closes https://www.pivotaltracker.com/story/show/107362814

Fix the maps chosen option

---

app/views/organizations/index.html.haml

Closes https://www.pivotaltracker.com/story/show/107363584

Added a registration button in organization index

---

app/controllers/projects_controller.rb
app/policies/project_policy.rb
app/views/projects/index.html.haml

Closes https://www.pivotaltracker.com/story/show/106883774

Added new project link in my projects view

---

app/models/organization.rb
app/models/project.rb

This adds capacity to filter projects with at least one project.

Added a new scope to organizaiton to search for projects

---

app/assets/javascripts/visitors.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_chosen.scss
app/assets/stylesheets/components/_forms.scss
app/assets/stylesheets/components/_landing.scss
app/controllers/organizations_controller.rb
app/controllers/visitors_controller.rb
app/views/organizations/index.html.haml
app/views/visitors/download_csv_project.csv.haml
app/views/visitors/index.html.haml
config/application.rb
config/locales/visitor.yml
config/routes.rb

https://www.pivotaltracker.com/story/show/107349798
https://www.pivotaltracker.com/story/show/104490652

Refactor map landing

---

app/controllers/visitors_controller.rb
app/views/visitors/index.html.haml

Cumple con:
- https://www.pivotaltracker.com/story/show/107347322

Link en el pin del mapa, redirige al proyecto correspondiente

---

app/assets/stylesheets/elements/_text.scss
app/views/visitors/index.html.haml

Closes https://www.pivotaltracker.com/story/show/107362814

Added a utility class to change text size

---

app/views/projects/_form.html.erb

Closes https://www.pivotaltracker.com/story/show/107338148

Fix a broken form link in the project's form

---

app/views/layouts/_footer.html.haml
db/schema.rb

https://www.pivotaltracker.com/story/show/107362896

quitar blank

---

app/assets/stylesheets/components/_multiple_showcase.scss

https://www.pivotaltracker.com/story/show/107412436

fondo blanco para las imagenes de cada showcase

---

app/assets/stylesheets/components/_investor_card.scss
app/assets/stylesheets/components/_organization_card.scss
app/assets/stylesheets/components/_project_card.scss
app/views/investors/index.html.haml

https://www.pivotaltracker.com/story/show/107411582

De un tamaño fijo a las cajas de los index

---

Gemfile
Gemfile.lock
app/controllers/visitors_controller.rb

https://www.pivotaltracker.com/story/show/107423202

saca coordendas de las direcciones de proyecto

---

app/views/visitors/index.html.haml

https://www.pivotaltracker.com/story/show/107433566

cambio de url de video

---

app/views/organizations/_profile.html.haml

Closes https://www.pivotaltracker.com/story/show/107437964

Uncommented unused functionality

---

app/controllers/investors_controller.rb
app/models/investor.rb
app/views/investors/_form.html.haml
app/views/investors/_profile.html.haml
config/locales/investor.yml
db/migrate/20151106002422_add_investment_type_investor.rb
db/schema.rb

Ya probe en local para solucionar este bug 
https://www.pivotaltracker.com/story/show/107437892
Y este bug (https://www.pivotaltracker.com/story/show/106798320 )es solucionado pero solo para el modelo de Investor, mandaré otro PR corrigiendo en todos los modelos

Fix investor

---

app/assets/stylesheets/components/_sub_navbar.scss
app/views/layouts/_sub_navbar.html.haml

Cumple con:
- https://www.pivotaltracker.com/story/show/107362866

Agrega icono de busqueda en searchbox

---

app/models/collaborator.rb
app/models/investor.rb
app/models/organization.rb
app/models/project.rb
db/schema.rb

https://www.pivotaltracker.com/story/show/106798320

Fix causes

---

app/views/layouts/menu/_no_session.html.haml
app/views/layouts/menu/_session.html.haml
config/locales/routes.es.yml
config/routes.rb

Cumple con:
- https://www.pivotaltracker.com/story/show/107441188

Cambia las rutas de sesión  a español

---

app/views/organizations/index.html.haml

Cumple con: 
- https://www.pivotaltracker.com/story/show/107408804

remueve boton cuando el usuario esta logueado

---

config/initializers/organization.rb
config/locales/organization.yml
db/schema.rb

https://www.pivotaltracker.com/story/show/107935348

agregar religion a las organizaciones

---

config/initializers/investor.rb
config/locales/investor.yml

https://www.pivotaltracker.com/story/show/107938364

gobierno como inversionista

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/components/_profile_project.scss
app/views/layouts/application.html.haml
app/views/layouts/profiles.html.haml
app/views/projects/_profile.html.haml
config/initializers/disqus_rails.rb

Cumple con: 
- [Como usuario puedo comentar en el perfil de un proyecto vía Disquss](https://www.pivotaltracker.com/story/show/103026484)

Agrega disqus a los proyectos

---

app/assets/stylesheets/components/_profile.scss

https://www.pivotaltracker.com/story/show/107749230

resize de la imagen de perfil

---

app/controllers/visitors_controller.rb

Bueno eran organizaciones aleatorios me confundi :( 
https://www.pivotaltracker.com/story/show/100581606

proyectos aleatorios en el landing

---

app/assets/javascripts/investors.coffee
app/controllers/investors_controller.rb
app/models/investor.rb
app/models/organization.rb
app/views/investors/_form.html.haml
app/views/investors/_profile.html.haml
app/views/layouts/_organizations.html.haml
config/locales/investor.yml
db/migrate/20151117223117_add_organization_to_investor.rb
db/schema.rb
spec/factories/investors.rb
spec/features/investors/add_organization_to_investor_spec.rb
spec/support/helpers/account.rb

https://www.pivotaltracker.com/story/show/107338156

Organization to investor

---

app/assets/stylesheets/components/_sub_navbar.scss
app/views/layouts/_sub_navbar.html.haml

Cumple con:
- [Agregar icono en searchbox de Navbar de explorar](https://www.pivotaltracker.com/story/show/107362866)

Corrige color y posición del glyphicon

---

app/assets/stylesheets/components/_landing.scss
app/views/visitors/index.html.haml

Cumple con:
- [Agregar cajita de Colaboradores en landing "Descubre"](https://www.pivotaltracker.com/story/show/107437486)

Agrega cajita de colaboradores

---

app/controllers/investors_controller.rb
app/models/investor.rb
app/views/investors/_profile.html.haml

https://www.pivotaltracker.com/story/show/109979474

se corrigio el bug que no permitia registrar como investor

---

app/controllers/visitors_controller.rb

https://www.pivotaltracker.com/story/show/107938570

mostrar en la lista solo proyectos activos

---

Gemfile
Gemfile.lock
app/controllers/projects_controller.rb
app/helpers/projects_helper.rb
config/initializers/causes.rb

Cumple con:
- [Búsqueda en searchbox con tags y descripción](https://www.pivotaltracker.com/story/show/109172142)

Agrega búsqueda basada en tags y descripción de causas

---

app/assets/stylesheets/components/_profile.scss
app/assets/stylesheets/components/_profile_project.scss
app/views/collaborators/_profile.html.haml
app/views/investors/_profile.html.haml
app/views/organizations/_profile.html.haml
app/views/projects/_profile.html.haml

Cumple con:
- [Alinear height en columna de imagen con columna de texto en perfiles](https://www.pivotaltracker.com/story/show/110003374)

Alinea el texto al borde de la imagen en los perfiles

---

app/views/events/index.html.haml
app/views/organizations/_profile.html.haml
app/views/projects/_empty_msg.html.haml
app/views/projects/index.html.haml
config/locales/event.yml
config/locales/project.yml

Cumple con:
- [Texto cuando no tienes proyectos y eventos](https://www.pivotaltracker.com/story/show/109978804)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/civica-digital/sociedad-actua/177)

Agrega mensaje cuando no se tienen proyectos o eventos.

---

app/views/organizations/_profile.html.haml
app/views/projects/index.html.haml
config/locales/project.yml

Corrige el bug:
- [Como organización no debo poder ver el botón de "Registrar proyecto" en el perfil de otra organización](https://www.pivotaltracker.com/story/show/109981272)
Cumple con:
- [Link "Ver Proyecto" en cada cajita de proyecto en vista de "Mis Proyectos"](https://www.pivotaltracker.com/story/show/109978920)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/civica-digital/sociedad-actua/175)

Ver proyecto desde la vista "Mis Proyectos"

---

app/assets/stylesheets/components/_landing.scss
app/views/organizations/_profile.html.haml

Cumple con:
- [Ajustar margin-bottom a 25px en sección Descubre organizaciones en landing page](https://www.pivotaltracker.com/story/show/109998674)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/civica-digital/sociedad-actua/176)

Ajustar margin-bottom a 25px en sección "Descubre".

---

app/assets/javascripts/application.js
app/assets/javascripts/third/jquery.fittext.js
app/assets/stylesheets/components/_project_card.scss
app/views/projects/list.html.haml

Cumple con:
- [Responsive text en grids](https://www.pivotaltracker.com/story/show/110000660)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/civica-digital/sociedad-actua/184)

Resize el texto en las cajitas

---

app/policies/investor_policy.rb
app/policies/organization_policy.rb

Fixes bug on organization profile
Bug: https://www.pivotaltracker.com/story/show/112690335

Fix update? policy in Organization & InvestorPolicy

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_landing.scss
app/assets/stylesheets/components/searchbox-bar.scss
app/views/visitors/index.html.haml

Cumple con:
- [Como usuario puedo ver un searchbox debajo del video del homepage](https://www.pivotaltracker.com/story/show/109997524)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/civica-digital/sociedad-actua/179)

Agrega searchbox debajo del video del homepage

---

app/assets/stylesheets/components/_landing.scss
app/views/visitors/index.html.haml

Cumple con:
- [Ajustar margin-bottom a 25px en sección Descubre organizaciones en landing page](https://www.pivotaltracker.com/story/show/109998674)

Agrega margin-bottom a subtitle

---

app/assets/stylesheets/components/_multiple_showcase.scss
app/assets/stylesheets/defaults/_colors.scss
app/views/investors/_profile.html.haml
config/locales/investor.yml

repara esto : 
https://www.pivotaltracker.com/story/show/112697139
y esto : 
https://www.pivotaltracker.com/story/show/109999610

Fixes , text investor translation & text color Showcase

---

app/controllers/events_controller.rb

Cumple con:
- [No puedo ver la página de eventos](https://www.pivotaltracker.com/story/show/113037835)

Corrige el acceso al listado de eventos

---

app/views/projects/_profile.html.haml
app/views/projects/index.html.haml
config/locales/project.yml

fix :  
https://www.pivotaltracker.com/story/show/113029667
& fix 
https://www.pivotaltracker.com/story/show/112690127

Fix missing translations

---

app/assets/stylesheets/components/_profile.scss
app/assets/stylesheets/components/_profile_project.scss
app/assets/stylesheets/defaults/_mixins.scss
app/views/organizations/_profile.html.haml

Cumple con:
- [Como usuario debo poder dar clic a los links en los perfiles](https://www.pivotaltracker.com/story/show/109981466)

Agrega link a las url de las organizaciones

---

app/views/visitors/index.html.haml

Cumple con:
- [Agrega eventos al landing](https://www.pivotaltracker.com/story/show/113048719)

agrega el elemento 'eventos' al landing

---

app/assets/stylesheets/components/_sub_navbar.scss
app/assets/stylesheets/framework_and_overrides.css.scss
app/views/layouts/application.html.haml
app/views/layouts/profiles.html.haml
app/views/projects/edit.html.haml
app/views/projects/index.html.haml
app/views/projects/new.html.haml
config/locales/project.yml

Profiles with subnavbar fluid and flash alerts

---

app/assets/stylesheets/components/_profile.scss
app/assets/stylesheets/components/_thumb.scss
app/views/layouts/_organizations.html.haml

Corrige:
- [Ajustar diseño de Grid de organizaciones en perfil de inversionista](https://www.pivotaltracker.com/story/show/113049239)

Corrige el grid de organizaciones

---

app/assets/javascripts/project.coffee
app/controllers/projects_controller.rb
app/models/project.rb
app/views/projects/_form.html.erb
app/views/projects/_profile.html.haml
db/migrate/20160208095725_add_collaboratorsto_projects.rb
db/schema.rb

Cumple con:
- [Como organización puedo agregar a otras organizaciones a un proyecto ](https://www.pivotaltracker.com/story/show/100579550)

Agrega organizaciones colaboradoras a proyectos

---

app/controllers/visitors_controller.rb
app/views/visitors/index.html.haml

solve: 
https://www.pivotaltracker.com/story/show/113099713

get city location when dont have projects

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_landing.scss
app/assets/stylesheets/components/_multiple_showcase.scss
app/assets/stylesheets/components/_sub_navbar.scss
app/assets/stylesheets/defaults/_mixins.scss
app/views/layouts/_sub_navbar.html.haml
app/views/layouts/application.html.haml
app/views/visitors/_showcase.html.haml
app/views/visitors/index.html.haml

cumple con:
- [Div con Background azul del mapa en landing page debe ocupar el 100% del width](https://www.pivotaltracker.com/story/show/109998332)
- [Reemplazar hamburguer-menu en barra de Explorar por searchbar en responsive](https://www.pivotaltracker.com/story/show/113049283)
- [Triángulo de contenedor de info con contenedor de imagen en sección de Descubre organizaciones en landing page](https://www.pivotaltracker.com/story/show/110000274)

100 width seccion del mapa

---

app/controllers/organizations_controller.rb
app/controllers/projects_controller.rb
app/models/organization.rb
app/views/layouts/_projects.html.haml
app/views/organizations/_form.html.haml
app/views/organizations/show.html.haml
config/locales/organization.yml
db/migrate/20160215093712_add_supports_to_organization.rb
db/migrate/20160215113124_add_funding_boolean_to_organization.rb
db/schema.rb

Cumple con:
- [Como usuario al seleccionar Grupos en landing me envía al index de organizaciones filtradas por tipo "Grupos"](https://www.pivotaltracker.com/story/show/113100633)
- [Como usuario puedo ver el perfil de los proyectos en colaboración en mi perfil](https://www.pivotaltracker.com/story/show/113481811)

Supports projects collab

---

config/locales/organization.yml
db/schema.rb

resuelve :
https://www.pivotaltracker.com/story/show/113099845

changes string for groups
